import 'dart:convert';
import 'vietnam_divisions_data.dart';

/// Dữ liệu hành chính 63 Tỉnh / Thành phố và các Quận / Huyện / Thị xã / Phường Xã trên toàn quốc Việt Nam.
/// Chuẩn hóa theo sơ đồ cơ sở dữ liệu `Địa điểm` (pkg_1) và Figma Tìm kiếm HomeShare.
class VietnamLocations {
  /// Danh sách 34 Tỉnh và Thành phố trực thuộc Trung ương của Việt Nam theo Nghị quyết số 202/2025/QH15.
  /// Gồm 6 Thành phố trực thuộc Trung ương và 28 Tỉnh thành sau sắp xếp.
  static const List<String> provinces34 = [
    'TP. Hồ Chí Minh',
    'Hà Nội',
    'Đà Nẵng',
    'Hải Phòng',
    'Cần Thơ',
    'Huế',
    'An Giang',
    'Bắc Ninh',
    'Cà Mau',
    'Cao Bằng',
    'Đắk Lắk',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Tĩnh',
    'Hưng Yên',
    'Khánh Hòa',
    'Lai Châu',
    'Lạng Sơn',
    'Lào Cai',
    'Lâm Đồng',
    'Nghệ An',
    'Ninh Bình',
    'Phú Thọ',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sơn La',
    'Tây Ninh',
    'Thái Nguyên',
    'Thanh Hóa',
    'Tuyên Quang',
    'Vĩnh Long',
  ];

  /// Danh sách đơn vị hành chính cấp tỉnh chính thức hiện hành (Chuẩn 34 Tỉnh / Thành phố mới)
  static const List<String> provinces = provinces34;

  /// Danh sách 63 Tỉnh và Thành phố cũ (lưu giữ để đối chiếu lịch sử)
  static const List<String> provinces63 = [
    'TP. Hồ Chí Minh',
    'Hà Nội',
    'Đà Nẵng',
    'Bình Dương',
    'Đồng Nai',
    'Cần Thơ',
    'Hải Phòng',
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bạc Liêu',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Định',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Cao Bằng',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Tĩnh',
    'Hải Dương',
    'Hậu Giang',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Long An',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
  ];

  /// Bản đồ phân cấp Quận / Huyện / Thị xã / Phường Xã cho từng Tỉnh / Thành phố
  static const Map<String, List<String>> _districtsMap = {
    'TP. Hồ Chí Minh': [
      'Tất cả',
      'Quận 1',
      'Quận 3',
      'Quận 4',
      'Quận 5',
      'Quận 6',
      'Quận 7',
      'Quận 8',
      'Quận 10',
      'Quận 11',
      'Quận 12',
      'Bình Thạnh',
      'Gò Vấp',
      'Phú Nhuận',
      'Tân Bình',
      'Tân Phú',
      'Bình Tân',
      'TP. Thủ Đức',
      'Huyện Bình Chánh',
      'Huyện Hóc Môn',
      'Huyện Củ Chi',
      'Huyện Nhà Bè',
      'Huyện Cần Giờ',
      'Phường Bến Nghé (Q1)',
      'Phường Bến Thành (Q1)',
      'Phường Tân Định (Q1)',
      'Phường 25 (Bình Thạnh)',
      'Phường 26 (Bình Thạnh)',
      'Phường Linh Trung (Thủ Đức)',
      'Phường Thảo Điền (Thủ Đức)',
      'Phường Hiệp Bình Chánh (Thủ Đức)',
      'Phường Tân Hưng (Q7)',
      'Phường Tân Phong (Q7)',
    ],
    'Hà Nội': [
      'Tất cả',
      'Quận Ba Đình',
      'Quận Hoàn Kiếm',
      'Quận Đống Đa',
      'Quận Cầu Giấy',
      'Quận Hai Bà Trưng',
      'Quận Hoàng Mai',
      'Quận Thanh Xuân',
      'Quận Long Biên',
      'Quận Nam Từ Liêm',
      'Quận Bắc Từ Liêm',
      'Quận Tây Hồ',
      'Quận Hà Đông',
      'Thị xã Sơn Tây',
      'Huyện Ba Vì',
      'Huyện Chương Mỹ',
      'Huyện Đan Phượng',
      'Huyện Đông Anh',
      'Huyện Gia Lâm',
      'Huyện Hoài Đức',
      'Huyện Mê Linh',
      'Huyện Mỹ Đức',
      'Huyện Phú Xuyên',
      'Huyện Phúc Thọ',
      'Huyện Quốc Oai',
      'Huyện Sóc Sơn',
      'Huyện Thạch Thất',
      'Huyện Thanh Oai',
      'Huyện Thanh Trì',
      'Huyện Thường Tín',
      'Huyện Ứng Hòa',
      'Phường Dịch Vọng Hậu (Cầu Giấy)',
      'Phường Bách Khoa (Hai Bà Trưng)',
      'Phường Khương Trung (Thanh Xuân)',
      'Phường Kim Mã (Ba Đình)',
      'Phường Hàng Trống (Hoàn Kiếm)',
      'Phường Láng Hạ (Đống Đa)',
    ],
    'Đà Nẵng': [
      'Tất cả',
      'Quận Hải Châu',
      'Quận Thanh Khê',
      'Quận Sơn Trà',
      'Quận Ngũ Hành Sơn',
      'Quận Liên Chiểu',
      'Quận Cẩm Lệ',
      'Huyện Hòa Vang',
      'Huyện Hoàng Sa',
      'Phường Hòa Cường Bắc',
      'Phường Thạch Thang',
      'Phường An Hải Bắc',
      'Phường Hòa Khánh Bắc',
    ],
    'Bình Dương': [
      'Tất cả',
      'TP. Thủ Dầu Một',
      'TP. Dĩ An',
      'TP. Thuận An',
      'TP. Tân Uyên',
      'TP. Bến Cát',
      'Huyện Bàu Bàng',
      'Huyện Bắc Tân Uyên',
      'Huyện Dầu Tiếng',
      'Huyện Phú Giáo',
      'Phường Đông Hòa (Dĩ An)',
      'Phường Lái Thiêu (Thuận An)',
      'Phường Phú Hòa (TDM)',
    ],
    'Đồng Nai': [
      'Tất cả',
      'TP. Biên Hòa',
      'TP. Long Khánh',
      'Huyện Cẩm Mỹ',
      'Huyện Định Quán',
      'Huyện Long Thành',
      'Huyện Nhơn Trạch',
      'Huyện Tân Phú',
      'Huyện Thống Nhất',
      'Huyện Trảng Bom',
      'Huyện Vĩnh Cửu',
      'Huyện Xuân Lộc',
      'Phường Tân Phong (Biên Hòa)',
      'Phường Trảng Dài (Biên Hòa)',
      'Phường Tam Hiệp (Biên Hòa)',
    ],
    'Cần Thơ': [
      'Tất cả',
      'Quận Ninh Kiều',
      'Quận Bình Thủy',
      'Quận Cái Răng',
      'Quận Ô Môn',
      'Quận Thốt Nốt',
      'Huyện Cờ Đỏ',
      'Huyện Phong Điền',
      'Huyện Thới Lai',
      'Huyện Vĩnh Thạnh',
      'Phường Xuân Khánh (Ninh Kiều)',
      'Phường An Khánh (Ninh Kiều)',
    ],
    'Hải Phòng': [
      'Tất cả',
      'Quận Hồng Bàng',
      'Quận Ngô Quyền',
      'Quận Lê Chân',
      'Quận Hải An',
      'Quận Kiến An',
      'Quận Đồ Sơn',
      'Quận Dương Kinh',
      'Huyện An Dương',
      'Huyện An Lão',
      'Huyện Bạch Long Vĩ',
      'Huyện Cát Hải',
      'Huyện Kiến Thụy',
      'Huyện Thủy Nguyên',
      'Huyện Tiên Lãng',
      'Huyện Vĩnh Bảo',
    ],
    'An Giang': [
      'Tất cả',
      'TP. Long Xuyên',
      'TP. Châu Đốc',
      'Thị xã Tân Châu',
      'Thị xã Tịnh Biên',
      'Huyện An Phú',
      'Huyện Châu Phú',
      'Huyện Châu Thành',
      'Huyện Chợ Mới',
      'Huyện Phú Tân',
      'Huyện Thoại Sơn',
      'Huyện Tri Tôn',
    ],
    'Bà Rịa - Vũng Tàu': [
      'Tất cả',
      'TP. Vũng Tàu',
      'TP. Bà Rịa',
      'Thị xã Phú Mỹ',
      'Huyện Châu Đức',
      'Huyện Côn Đảo',
      'Huyện Đất Đỏ',
      'Huyện Long Điền',
      'Huyện Xuyên Mộc',
    ],
    'Bắc Giang': [
      'Tất cả',
      'TP. Bắc Giang',
      'Thị xã Việt Yên',
      'Huyện Hiệp Hòa',
      'Huyện Lạng Giang',
      'Huyện Lục Nam',
      'Huyện Lục Ngạn',
      'Huyện Sơn Động',
      'Huyện Tân Yên',
      'Huyện Yên Dũng',
      'Huyện Yên Thế',
    ],
    'Bắc Kạn': [
      'Tất cả',
      'TP. Bắc Kạn',
      'Huyện Ba Bể',
      'Huyện Bạch Thông',
      'Huyện Chợ Đồn',
      'Huyện Chợ Mới',
      'Huyện Na Rì',
      'Huyện Ngân Sơn',
      'Huyện Pác Nặm',
    ],
    'Bạc Liêu': [
      'Tất cả',
      'TP. Bạc Liêu',
      'Thị xã Giá Rai',
      'Huyện Đông Hải',
      'Huyện Hòa Bình',
      'Huyện Hồng Dân',
      'Huyện Phước Long',
      'Huyện Vĩnh Lợi',
    ],
    'Bắc Ninh': [
      'Tất cả',
      'TP. Bắc Ninh',
      'TP. Từ Sơn',
      'Thị xã Quế Võ',
      'Thị xã Thuận Thành',
      'Huyện Gia Bình',
      'Huyện Lương Tài',
      'Huyện Tiên Du',
      'Huyện Yên Phong',
    ],
    'Bến Tre': [
      'Tất cả',
      'TP. Bến Tre',
      'Huyện Ba Tri',
      'Huyện Bình Đại',
      'Huyện Châu Thành',
      'Huyện Chợ Lách',
      'Huyện Giồng Trôm',
      'Huyện Mỏ Cày Bắc',
      'Huyện Mỏ Cày Nam',
      'Huyện Thạnh Phú',
    ],
    'Bình Định': [
      'Tất cả',
      'TP. Quy Nhơn',
      'Thị xã An Nhơn',
      'Thị xã Hoài Nhơn',
      'Huyện An Lão',
      'Huyện Hoài Ân',
      'Huyện Phù Cát',
      'Huyện Phù Mỹ',
      'Huyện Tuy Phước',
      'Huyện Tây Sơn',
      'Huyện Vân Canh',
      'Huyện Vĩnh Thạnh',
    ],
    'Bình Phước': [
      'Tất cả',
      'TP. Đồng Xoài',
      'Thị xã Bình Long',
      'Thị xã Chơn Thành',
      'Thị xã Phước Long',
      'Huyện Bù Đăng',
      'Huyện Bù Đốp',
      'Huyện Bù Gia Mập',
      'Huyện Đồng Phú',
      'Huyện Hớn Quản',
      'Huyện Lộc Ninh',
      'Huyện Phú Riềng',
    ],
    'Bình Thuận': [
      'Tất cả',
      'TP. Phan Thiết',
      'Thị xã La Gi',
      'Huyện Bắc Bình',
      'Huyện Đức Linh',
      'Huyện Hàm Tân',
      'Huyện Hàm Thuận Bắc',
      'Huyện Hàm Thuận Nam',
      'Huyện Phú Quý',
      'Huyện Tánh Linh',
      'Huyện Tuy Phong',
    ],
    'Cà Mau': [
      'Tất cả',
      'TP. Cà Mau',
      'Huyện Cái Nước',
      'Huyện Đầm Dơi',
      'Huyện Năm Căn',
      'Huyện Ngọc Hiển',
      'Huyện Phú Tân',
      'Huyện Thới Bình',
      'Huyện Trần Văn Thời',
      'Huyện U Minh',
    ],
    'Cao Bằng': [
      'Tất cả',
      'TP. Cao Bằng',
      'Huyện Bảo Lạc',
      'Huyện Bảo Lâm',
      'Huyện Hạ Lang',
      'Huyện Hà Quảng',
      'Huyện Hòa An',
      'Huyện Nguyên Bình',
      'Huyện Quảng Hòa',
      'Huyện Thạch An',
      'Huyện Trùng Khánh',
    ],
    'Đắk Lắk': [
      'Tất cả',
      'TP. Buôn Ma Thuột',
      'Thị xã Buôn Hồ',
      'Huyện Buôn Đôn',
      'Huyện Cư Kuin',
      'Huyện Cư M\'gar',
      'Huyện Ea H\'leo',
      'Huyện Ea Kar',
      'Huyện Ea Súp',
      'Huyện Krông Ana',
      'Huyện Krông Bông',
      'Huyện Krông Búk',
      'Huyện Krông Năng',
      'Huyện Krông Pắc',
      'Huyện Lắk',
      'Huyện M\'Drắk',
    ],
    'Đắk Nông': [
      'Tất cả',
      'TP. Gia Nghĩa',
      'Huyện Cư Jút',
      'Huyện Đắk Glong',
      'Huyện Đắk Mil',
      'Huyện Đắk R\'lấp',
      'Huyện Đắk Song',
      'Huyện Krông Nô',
      'Huyện Tuy Đức',
    ],
    'Điện Biên': [
      'Tất cả',
      'TP. Điện Biên Phủ',
      'Thị xã Mường Lay',
      'Huyện Điện Biên',
      'Huyện Điện Biên Đông',
      'Huyện Mường Ảng',
      'Huyện Mường Chà',
      'Huyện Mường Nhé',
      'Huyện Nậm Pồ',
      'Huyện Tủa Chùa',
      'Huyện Tuần Giáo',
    ],
    'Đồng Tháp': [
      'Tất cả',
      'TP. Cao Lãnh',
      'TP. Sa Đéc',
      'TP. Hồng Ngự',
      'Huyện Cao Lãnh',
      'Huyện Châu Thành',
      'Huyện Hồng Ngự',
      'Huyện Lai Vung',
      'Huyện Lấp Vò',
      'Huyện Tam Nông',
      'Huyện Tân Hồng',
      'Huyện Thanh Bình',
      'Huyện Tháp Mười',
    ],
    'Gia Lai': [
      'Tất cả',
      'TP. Pleiku',
      'Thị xã An Khê',
      'Thị xã Ayun Pa',
      'Huyện Chư Păh',
      'Huyện Chư Prông',
      'Huyện Chư Pưh',
      'Huyện Chư Sê',
      'Huyện Đắk Đoa',
      'Huyện Đắk Pơ',
      'Huyện Đức Cơ',
      'Huyện Ia Grai',
      'Huyện Ia Pa',
      'Huyện K\'Bang',
      'Huyện Kông Chro',
      'Huyện Krông Pa',
      'Huyện Mang Yang',
      'Huyện Phú Thiện',
    ],
    'Hà Giang': [
      'Tất cả',
      'TP. Hà Giang',
      'Huyện Bắc Mê',
      'Huyện Bắc Quang',
      'Huyện Đồng Văn',
      'Huyện Hoàng Su Phì',
      'Huyện Mèo Vạc',
      'Huyện Quản Bạ',
      'Huyện Quang Bình',
      'Huyện Vị Xuyên',
      'Huyện Xín Mần',
      'Huyện Yên Minh',
    ],
    'Hà Nam': [
      'Tất cả',
      'TP. Phủ Lý',
      'Thị xã Duy Tiên',
      'Huyện Bình Lục',
      'Huyện Kim Bảng',
      'Huyện Lý Nhân',
      'Huyện Thanh Liêm',
    ],
    'Hà Tĩnh': [
      'Tất cả',
      'TP. Hà Tĩnh',
      'Thị xã Hồng Lĩnh',
      'Thị xã Kỳ Anh',
      'Huyện Cẩm Xuyên',
      'Huyện Can Lộc',
      'Huyện Đức Thọ',
      'Huyện Hương Khê',
      'Huyện Hương Sơn',
      'Huyện Kỳ Anh',
      'Huyện Lộc Hà',
      'Huyện Nghi Xuân',
      'Huyện Thạch Hà',
      'Huyện Vũ Quang',
    ],
    'Hải Dương': [
      'Tất cả',
      'TP. Hải Dương',
      'TP. Chí Linh',
      'Thị xã Kinh Môn',
      'Huyện Bình Giang',
      'Huyện Cẩm Giàng',
      'Huyện Gia Lộc',
      'Huyện Kim Thành',
      'Huyện Nam Sách',
      'Huyện Ninh Giang',
      'Huyện Thanh Hà',
      'Huyện Thanh Miện',
      'Huyện Tứ Kỳ',
    ],
    'Hậu Giang': [
      'Tất cả',
      'TP. Vị Thanh',
      'TP. Ngã Bảy',
      'Thị xã Long Mỹ',
      'Huyện Châu Thành',
      'Huyện Châu Thành A',
      'Huyện Long Mỹ',
      'Huyện Phụng Hiệp',
      'Huyện Vị Thủy',
    ],
    'Hòa Bình': [
      'Tất cả',
      'TP. Hòa Bình',
      'Huyện Cao Phong',
      'Huyện Đà Bắc',
      'Huyện Kim Bôi',
      'Huyện Lạc Sơn',
      'Huyện Lạc Thủy',
      'Huyện Lương Sơn',
      'Huyện Mai Châu',
      'Huyện Tân Lạc',
      'Huyện Yên Thủy',
    ],
    'Hưng Yên': [
      'Tất cả',
      'TP. Hưng Yên',
      'Thị xã Mỹ Hào',
      'Huyện Ân Thi',
      'Huyện Khoái Châu',
      'Huyện Kim Động',
      'Huyện Phù Cừ',
      'Huyện Tiên Lữ',
      'Huyện Văn Giang',
      'Huyện Văn Lâm',
      'Huyện Yên Mỹ',
    ],
    'Khánh Hòa': [
      'Tất cả',
      'TP. Nha Trang',
      'TP. Cam Ranh',
      'Thị xã Ninh Hòa',
      'Huyện Cam Lâm',
      'Huyện Diên Khánh',
      'Huyện Khánh Sơn',
      'Huyện Khánh Vĩnh',
      'Huyện Trường Sa',
      'Huyện Vạn Ninh',
    ],
    'Kiên Giang': [
      'Tất cả',
      'TP. Rạch Giá',
      'TP. Hà Tiên',
      'TP. Phú Quốc',
      'Huyện An Biên',
      'Huyện An Minh',
      'Huyện Châu Thành',
      'Huyện Giang Thành',
      'Huyện Giồng Riềng',
      'Huyện Gò Quao',
      'Huyện Hòn Đất',
      'Huyện Kiên Hải',
      'Huyện Kiên Lương',
      'Huyện Tân Hiệp',
      'Huyện U Minh Thượng',
      'Huyện Vĩnh Thuận',
    ],
    'Kon Tum': [
      'Tất cả',
      'TP. Kon Tum',
      'Huyện Đắk Glei',
      'Huyện Đắk Hà',
      'Huyện Đắk Tô',
      'Huyện Ia H\'Drai',
      'Huyện Kon Plông',
      'Huyện Kon Rẫy',
      'Huyện Ngọc Hồi',
      'Huyện Sa Thầy',
      'Huyện Tu Mơ Rông',
    ],
    'Lai Châu': [
      'Tất cả',
      'TP. Lai Châu',
      'Huyện Mường Tè',
      'Huyện Nậm Nhùn',
      'Huyện Phong Thổ',
      'Huyện Sìn Hồ',
      'Huyện Tam Đường',
      'Huyện Tân Uyên',
      'Huyện Than Uyên',
    ],
    'Lâm Đồng': [
      'Tất cả',
      'TP. Đà Lạt',
      'TP. Bảo Lộc',
      'Huyện Bảo Lâm',
      'Huyện Cát Tiên',
      'Huyện Di Linh',
      'Huyện Đạ Huoai',
      'Huyện Đạ Tẻh',
      'Huyện Đam Rông',
      'Huyện Đơn Dương',
      'Huyện Đức Trọng',
      'Huyện Lạc Dương',
      'Huyện Lâm Hà',
    ],
    'Lạng Sơn': [
      'Tất cả',
      'TP. Lạng Sơn',
      'Huyện Bắc Sơn',
      'Huyện Bình Gia',
      'Huyện Cao Lộc',
      'Huyện Chi Lăng',
      'Huyện Đình Lập',
      'Huyện Hữu Lũng',
      'Huyện Lộc Bình',
      'Huyện Tràng Định',
      'Huyện Văn Lãng',
      'Huyện Văn Quan',
    ],
    'Lào Cai': [
      'Tất cả',
      'TP. Lào Cai',
      'Thị xã Sa Pa',
      'Huyện Bát Xát',
      'Huyện Bảo Thắng',
      'Huyện Bảo Yên',
      'Huyện Bắc Hà',
      'Huyện Mường Khương',
      'Huyện Si Ma Cai',
      'Huyện Văn Bàn',
    ],
    'Long An': [
      'Tất cả',
      'TP. Tân An',
      'Thị xã Kiến Tường',
      'Huyện Bến Lức',
      'Huyện Cần Đước',
      'Huyện Cần Giuộc',
      'Huyện Châu Thành',
      'Huyện Đức Hòa',
      'Huyện Đức Huệ',
      'Huyện Mộc Hóa',
      'Huyện Tân Hưng',
      'Huyện Tân Thạnh',
      'Huyện Tân Trụ',
      'Huyện Thạnh Hóa',
      'Huyện Thủ Thừa',
      'Huyện Vĩnh Hưng',
    ],
    'Nam Định': [
      'Tất cả',
      'TP. Nam Định',
      'Huyện Giao Thủy',
      'Huyện Hải Hậu',
      'Huyện Mỹ Lộc',
      'Huyện Nam Trực',
      'Huyện Nghĩa Hưng',
      'Huyện Trực Ninh',
      'Huyện Vụ Bản',
      'Huyện Xuân Trường',
      'Huyện Ý Yên',
    ],
    'Nghệ An': [
      'Tất cả',
      'TP. Vinh',
      'Thị xã Cửa Lò',
      'Thị xã Hoàng Mai',
      'Thị xã Thái Hòa',
      'Huyện Anh Sơn',
      'Huyện Con Cuông',
      'Huyện Diễn Châu',
      'Huyện Đô Lương',
      'Huyện Hưng Nguyên',
      'Huyện Kỳ Sơn',
      'Huyện Nam Đàn',
      'Huyện Nghi Lộc',
      'Huyện Nghĩa Đàn',
      'Huyện Quế Phong',
      'Huyện Quỳ Châu',
      'Huyện Quỳ Hợp',
      'Huyện Quỳnh Lưu',
      'Huyện Tân Kỳ',
      'Huyện Thanh Chương',
      'Huyện Tương Dương',
      'Huyện Yên Thành',
    ],
    'Ninh Bình': [
      'Tất cả',
      'TP. Ninh Bình',
      'TP. Tam Điệp',
      'Huyện Gia Viễn',
      'Huyện Hoa Lư',
      'Huyện Kim Sơn',
      'Huyện Nho Quan',
      'Huyện Yên Khánh',
      'Huyện Yên Mô',
    ],
    'Ninh Thuận': [
      'Tất cả',
      'TP. Phan Rang - Tháp Chàm',
      'Huyện Bác Ái',
      'Huyện Ninh Hải',
      'Huyện Ninh Phước',
      'Huyện Ninh Sơn',
      'Huyện Thuận Bắc',
      'Huyện Thuận Nam',
    ],
    'Phú Thọ': [
      'Tất cả',
      'TP. Việt Trì',
      'Thị xã Phú Thọ',
      'Huyện Cẩm Khê',
      'Huyện Đoan Hùng',
      'Huyện Hạ Hòa',
      'Huyện Lâm Thao',
      'Huyện Phù Ninh',
      'Huyện Tam Nông',
      'Huyện Tân Sơn',
      'Huyện Thanh Ba',
      'Huyện Thanh Sơn',
      'Huyện Thanh Thủy',
      'Huyện Yên Lập',
    ],
    'Phú Yên': [
      'Tất cả',
      'TP. Tuy Hòa',
      'Thị xã Sông Cầu',
      'Thị xã Đông Hòa',
      'Huyện Đồng Xuân',
      'Huyện Phú Hòa',
      'Huyện Sơn Hòa',
      'Huyện Sông Hinh',
      'Huyện Tây Hòa',
      'Huyện Tuy An',
    ],
    'Quảng Bình': [
      'Tất cả',
      'TP. Đồng Hới',
      'Thị xã Ba Đồn',
      'Huyện Bố Trạch',
      'Huyện Lệ Thủy',
      'Huyện Minh Hóa',
      'Huyện Quảng Ninh',
      'Huyện Quảng Trạch',
      'Huyện Tuyên Hóa',
    ],
    'Quảng Nam': [
      'Tất cả',
      'TP. Tam Kỳ',
      'TP. Hội An',
      'Thị xã Điện Bàn',
      'Huyện Bắc Trà My',
      'Huyện Duy Xuyên',
      'Huyện Đại Lộc',
      'Huyện Đông Giang',
      'Huyện Hiệp Đức',
      'Huyện Nam Giang',
      'Huyện Nam Trà My',
      'Huyện Nông Sơn',
      'Huyện Núi Thành',
      'Huyện Phú Ninh',
      'Huyện Phước Sơn',
      'Huyện Quế Sơn',
      'Huyện Tây Giang',
      'Huyện Thăng Bình',
      'Huyện Tiên Phước',
    ],
    'Quảng Ngãi': [
      'Tất cả',
      'TP. Quảng Ngãi',
      'Thị xã Đức Phổ',
      'Huyện Ba Tơ',
      'Huyện Bình Sơn',
      'Huyện Lý Sơn',
      'Huyện Minh Long',
      'Huyện Mộ Đức',
      'Huyện Nghĩa Hành',
      'Huyện Sơn Hà',
      'Huyện Sơn Tây',
      'Huyện Sơn Tịnh',
      'Huyện Trà Bồng',
      'Huyện Tư Nghĩa',
    ],
    'Quảng Ninh': [
      'Tất cả',
      'TP. Hạ Long',
      'TP. Cẩm Phả',
      'TP. Móng Cái',
      'TP. Uông Bí',
      'TP. Đông Triều',
      'Thị xã Quảng Yên',
      'Huyện Ba Chẽ',
      'Huyện Bình Liêu',
      'Huyện Cô Tô',
      'Huyện Đầm Hà',
      'Huyện Hải Hà',
      'Huyện Tiên Yên',
      'Huyện Vân Đồn',
    ],
    'Quảng Trị': [
      'Tất cả',
      'TP. Đông Hà',
      'Thị xã Quảng Trị',
      'Huyện Cam Lộ',
      'Huyện Cồn Cỏ',
      'Huyện Đakrông',
      'Huyện Gio Linh',
      'Huyện Hải Lăng',
      'Huyện Hướng Hóa',
      'Huyện Triệu Phong',
      'Huyện Vĩnh Linh',
    ],
    'Sóc Trăng': [
      'Tất cả',
      'TP. Sóc Trăng',
      'Thị xã Ngã Năm',
      'Thị xã Vĩnh Châu',
      'Huyện Châu Thành',
      'Huyện Cù Lao Dung',
      'Huyện Kế Sách',
      'Huyện Long Phú',
      'Huyện Mỹ Tú',
      'Huyện Mỹ Xuyên',
      'Huyện Thạnh Trị',
      'Huyện Trần Đề',
    ],
    'Sơn La': [
      'Tất cả',
      'TP. Sơn La',
      'Huyện Bắc Yên',
      'Huyện Mai Sơn',
      'Huyện Mộc Châu',
      'Huyện Mường La',
      'Huyện Phù Yên',
      'Huyện Quỳnh Nhai',
      'Huyện Sông Mã',
      'Huyện Sốp Cộp',
      'Huyện Thuận Châu',
      'Huyện Vân Hồ',
      'Huyện Yên Châu',
    ],
    'Tây Ninh': [
      'Tất cả',
      'TP. Tây Ninh',
      'Thị xã Trảng Bàng',
      'Thị xã Hòa Thành',
      'Huyện Bến Cầu',
      'Huyện Châu Thành',
      'Huyện Dương Minh Châu',
      'Huyện Gò Dầu',
      'Huyện Tân Biên',
      'Huyện Tân Châu',
    ],
    'Thái Bình': [
      'Tất cả',
      'TP. Thái Bình',
      'Huyện Đông Hưng',
      'Huyện Hưng Hà',
      'Huyện Kiến Xương',
      'Huyện Quỳnh Phụ',
      'Huyện Thái Thụy',
      'Huyện Tiền Hải',
      'Huyện Vũ Thư',
    ],
    'Thái Nguyên': [
      'Tất cả',
      'TP. Thái Nguyên',
      'TP. Sông Công',
      'TP. Phổ Yên',
      'Huyện Đại Từ',
      'Huyện Định Hóa',
      'Huyện Đồng Hỷ',
      'Huyện Phú Bình',
      'Huyện Phú Lương',
      'Huyện Võ Nhai',
    ],
    'Thanh Hóa': [
      'Tất cả',
      'TP. Thanh Hóa',
      'TP. Sầm Sơn',
      'Thị xã Bỉm Sơn',
      'Thị xã Nghi Sơn',
      'Huyện Bá Thước',
      'Huyện Cẩm Thủy',
      'Huyện Đông Sơn',
      'Huyện Hà Trung',
      'Huyện Hậu Lộc',
      'Huyện Hoằng Hóa',
      'Huyện Lang Chánh',
      'Huyện Mường Lát',
      'Huyện Nga Sơn',
      'Huyện Ngọc Lặc',
      'Huyện Như Thanh',
      'Huyện Như Xuân',
      'Huyện Nông Cống',
      'Huyện Quan Hóa',
      'Huyện Quan Sơn',
      'Huyện Quảng Xương',
      'Huyện Thạch Thành',
      'Huyện Thiệu Hóa',
      'Huyện Thọ Xuân',
      'Huyện Thường Xuân',
      'Huyện Triệu Sơn',
      'Huyện Vĩnh Lộc',
      'Huyện Yên Định',
    ],
    'Thừa Thiên Huế': [
      'Tất cả',
      'TP. Huế',
      'Thị xã Hương Thủy',
      'Thị xã Hương Trà',
      'Huyện A Lưới',
      'Huyện Nam Đông',
      'Huyện Phong Điền',
      'Huyện Phú Lộc',
      'Huyện Phú Vang',
      'Huyện Quảng Điền',
    ],
    'Tiền Giang': [
      'Tất cả',
      'TP. Mỹ Tho',
      'Thị xã Gò Công',
      'Thị xã Cai Lậy',
      'Huyện Cái Bè',
      'Huyện Cai Lậy',
      'Huyện Châu Thành',
      'Huyện Chợ Gạo',
      'Huyện Gò Công Đông',
      'Huyện Gò Công Tây',
      'Huyện Tân Phú Đông',
      'Huyện Tân Phước',
    ],
    'Trà Vinh': [
      'Tất cả',
      'TP. Trà Vinh',
      'Thị xã Duyên Hải',
      'Huyện Càng Long',
      'Huyện Cầu Kè',
      'Huyện Cầu Ngang',
      'Huyện Châu Thành',
      'Huyện Duyên Hải',
      'Huyện Tiểu Cần',
      'Huyện Trà Cú',
    ],
    'Tuyên Quang': [
      'Tất cả',
      'TP. Tuyên Quang',
      'Huyện Chiêm Hóa',
      'Huyện Hàm Yên',
      'Huyện Lâm Bình',
      'Huyện Na Hang',
      'Huyện Sơn Dương',
      'Huyện Yên Sơn',
    ],
    'Vĩnh Long': [
      'Tất cả',
      'TP. Vĩnh Long',
      'Thị xã Bình Minh',
      'Huyện Bình Tân',
      'Huyện Long Hồ',
      'Huyện Mang Thít',
      'Huyện Tam Bình',
      'Huyện Trà Ôn',
      'Huyện Vũng Liêm',
    ],
    'Vĩnh Phúc': [
      'Tất cả',
      'TP. Vĩnh Yên',
      'TP. Phúc Yên',
      'Huyện Bình Xuyên',
      'Huyện Lập Thạch',
      'Huyện Sông Lô',
      'Huyện Tam Đảo',
      'Huyện Tam Dương',
      'Huyện Vĩnh Tường',
      'Huyện Yên Lạc',
    ],
    'Yên Bái': [
      'Tất cả',
      'TP. Yên Bái',
      'Thị xã Nghĩa Lộ',
      'Huyện Lục Yên',
      'Huyện Mù Cang Chải',
      'Huyện Trạm Tấu',
      'Huyện Trấn Yên',
      'Huyện Văn Chấn',
      'Huyện Văn Yên',
      'Huyện Yên Bình',
    ],
  };

  /// Lấy danh sách Quận / Huyện / Phường / Xã tương ứng theo Tỉnh / Thành phố (dùng cho bộ lọc tìm kiếm)
  static List<String> getDistricts(String province) {
    if (province == 'Huế' && _districtsMap.containsKey('Thừa Thiên Huế')) {
      return _districtsMap['Thừa Thiên Huế']!;
    }
    return _districtsMap[province] ?? const ['Tất cả'];
  }

  // ===========================================================================
  // DỮ LIỆU ĐẦY ĐỦ 3 CẤP HÀNH CHÍNH (TỈNH/TP -> QUẬN/HUYỆN -> PHƯỜNG/XÃ)
  // ===========================================================================
  static Map<String, Map<String, List<String>>>? _fullHierarchy;

  /// Nạp và cache dữ liệu phân cấp hành chính toàn quốc từ bộ nhớ
  static void _ensureLoaded() {
    if (_fullHierarchy != null) return;
    try {
      final decoded =
          jsonDecode(vietnamDivisionsRawJson) as Map<String, dynamic>;
      final map = <String, Map<String, List<String>>>{};
      decoded.forEach((provKey, distMapRaw) {
        final distMap = <String, List<String>>{};
        if (distMapRaw is Map) {
          distMapRaw.forEach((distKey, wardsRaw) {
            if (wardsRaw is List) {
              distMap[distKey.toString()] = wardsRaw
                  .map((e) => e.toString())
                  .toList();
            }
          });
        }
        map[provKey] = distMap;
      });
      _fullHierarchy = map;
    } catch (_) {
      _fullHierarchy = {};
    }
  }

  /// Lấy danh sách Quận / Huyện chính xác của một Tỉnh / Thành phố
  static List<String> getAdministrativeDistricts(String province) {
    _ensureLoaded();
    final distMap = _fullHierarchy?[province];
    if (distMap != null && distMap.isNotEmpty) {
      final list = distMap.keys.toList();
      list.sort((a, b) => a.compareTo(b));
      return list;
    }
    // Fallback sang _districtsMap nếu cần
    final fallback = _districtsMap[province] ?? const [];
    return fallback
        .where((d) => d != 'Tất cả' && !d.startsWith('Phường '))
        .toList();
  }

  /// Lấy danh sách đầy đủ Phường / Xã / Thị trấn theo Tỉnh / Thành phố và Quận / Huyện
  static List<String> getWards(String province, String district) {
    _ensureLoaded();
    final distMap = _fullHierarchy?[province];
    if (distMap == null || distMap.isEmpty) return const [];

    // Tìm kiếm trực tiếp theo tên quận huyện
    if (distMap.containsKey(district)) {
      return distMap[district]!;
    }

    // Tìm kiếm linh hoạt (bỏ tiền tố "Quận ", "Huyện ", "Thị xã " hoặc tìm chứa)
    final cleanDistrict = district
        .replaceAll('Quận ', '')
        .replaceAll('Huyện ', '')
        .replaceAll('Thị xã ', '')
        .replaceAll('TP. ', '')
        .replaceAll('Thành phố ', '')
        .trim()
        .toLowerCase();

    for (final entry in distMap.entries) {
      final entryClean = entry.key
          .replaceAll('Quận ', '')
          .replaceAll('Huyện ', '')
          .replaceAll('Thị xã ', '')
          .replaceAll('TP. ', '')
          .replaceAll('Thành phố ', '')
          .trim()
          .toLowerCase();

      if (entryClean == cleanDistrict ||
          entry.key.toLowerCase().contains(cleanDistrict) ||
          cleanDistrict.contains(entryClean)) {
        return entry.value;
      }
    }

    return const [];
  }
}
